### ISSUE TITLE
20180511

### ISSUE THREAD

**Issue by NomotoEriko** [OnizukaLab/100knock#25]
# みんなで情報共有（第1, 2 章）
良さげな書き方とかメモとかをコメントしていきましょう！！

**Comment by NomotoEriko** [comment]
[メモ] Atomは楽しい Atomic power combo 

<- active-power-mode

**Comment by NomotoEriko** [comment]
### q00
```
"".join([i for i in reversed("stressed")])
"".join(list(reversed("stressed"))
```
こういう書き方もできる

**Comment by NomotoEriko** [comment]
## q02
`"".join(c1 + c2 for c1, c2 in zip("パトカー",  "タクシー"))`
こういう書き方もできる

**Comment by tarohi24** [comment]
## q05
```
def make_ngram(lst, n=2, is_word_ngram=True):
    """
    n-gram
    @param lst 単語n-gramなら単語のリスト,
    """
    if len(lst) <= (n-1):
        return []
    else:
        return [lst[0:n]] + make_ngram(lst[1:], n, is_word_ngram)
```
再帰で書くとすっきりする例?

**Comment by NomotoEriko** [comment]
### q05
```
bi-gramの作り方
[i+j for i, j in zip(seq, seq[1:])]
```
こういうのも好き．

**Comment by KAWAYu** [comment]
`yield` 使うとメモリ消費を抑えられる
```
def ngram(l, n=2):
  for i in range(len(l) - n + 1):
    yield l[i:i+n]
```
参考までに

**Comment by tanaka504** [comment]
numpy の permutation を使ってシャッフルされたインデックスを使っても
解ける？

<- numpy 使いなれてたら良さげ

**Comment by NomotoEriko** [comment]
### q08
```
a = [1, 2, 3, 4, 5]
random.shuffle(a)
```
はaをシャッフルするのでaをシャッフルしたものを返すわけではないので使えない...と思いきや！！
`b = a[1:-1]`
は新しいリストbが作られるので
aを破壊しない．（b = a はアウト）

**Comment by KAWAYu** [comment]
with のなかの色々は並べられる！

**Comment by NomotoEriko** [comment]
### q13
`print("hoge", f=fw)`
でもファイル書き込みできる．

**Comment by bmiura** [comment]
### q16
all個をn分割するときに何個ずつ分けるといい感じになるかのリストが作れる
`[(all+i)//n for i in range(n)]`

**Comment by NomotoEriko** [comment]
かっこいい！！！
